### ISSUE TITLE
Что не так?

### ISSUE THREAD

**Issue by lp85d** [everythingishacked/Pants#1]
```
Microsoft Windows [Version 10.0.22631.3737]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Windows\System32>cd C:\Users\lp85d\Desktop\Pants-master

C:\Users\lp85d\Desktop\Pants-master>python pantser.py -h
Traceback (most recent call last):
  File "C:\Users\lp85d\Desktop\Pants-master\pantser.py", line 3, in <module>
    import pyvirtualcam
ModuleNotFoundError: No module named 'pyvirtualcam'

C:\Users\lp85d\Desktop\Pants-master>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement mediapipe==0.8.9.1 (from versions: 0.10.1, 0.10.2, 0.10.3, 0.10.5, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.13, 0.10.14)
ERROR: No matching distribution found for mediapipe==0.8.9.1

[notice] A new release of pip available: 22.3 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\lp85d\Desktop\Pants-master>python pantser.py -h
Traceback (most recent call last):
  File "C:\Users\lp85d\Desktop\Pants-master\pantser.py", line 3, in <module>
    import pyvirtualcam
ModuleNotFoundError: No module named 'pyvirtualcam'

C:\Users\lp85d\Desktop\Pants-master>
```

**Comment by everythingishacked** [comment]
> ModuleNotFoundError: No module named 'pyvirtualcam'

`pip install pyvirtualcam`

**Comment by lp85d** [comment]
А вот тут у вас не полная инструкция
Вот что нужно было делать:
1. Установить [(https://cdn-fastly.obsproject.com/downloads/OBS-Studio-30.1.2-Full-Installer-x64.exe)]
2. Закрыть программы использующие камеру
3. Исправить requirements.txt
```
mediapipe==0.10.14
opencv_contrib_python==4.5.5.64
pyvirtualcam==0.11.1
```
4. Запустить установку pip install -r requirements.txt
5. Запустить программу 
pantser.py --input 0 --pants 1 --width 0.6 --flip 1 --landmarks 1 --record 1

**Comment by lp85d** [comment]
![image](https://github.com/everythingishacked/Pants/assets/3320759/067df0c3-b18b-440b-91c1-91e218f18ef1)
